/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package document_tracking_system;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import java.sql.*;
import java.util.HashMap;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author Admin
 */
public class LogInPage extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public LogInPage() {
        initComponents();

        //  jButtonSubmit.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6dd = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jButtonSubmit = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabelUserId = new javax.swing.JLabel();
        jLabelTodata = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabelUsername = new javax.swing.JLabel();
        jLabelSSID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Copyright 2019 DoRsu all right reserve ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Document tracking system version 1.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(156, 156, 156))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6dd.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(204, 102, 0));
        jPanel7.setForeground(new java.awt.Color(204, 102, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jSeparator4.setBackground(new java.awt.Color(0, 51, 102));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Login(School Personel Group)");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel15.setText("Username:");

        jTextFieldUsername.setNextFocusableComponent(jPasswordFieldPassword);
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel16.setText("Password:");

        jButtonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_tracking_system/images/cheek.png"))); // NOI18N
        jButtonSubmit.setText("Login");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jButtonSubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonSubmitKeyReleased(evt);
            }
        });

        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_tracking_system/images/register.png"))); // NOI18N
        jButtonLogin.setText("Register");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jPasswordFieldPassword.setNextFocusableComponent(jButtonSubmit);
        jPasswordFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldPasswordKeyReleased(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_tracking_system/images/log.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("The Davao Oriental State University");

        jLabel37.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 102, 0));
        jLabel37.setText("(DOrSU) ");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Log in DTS Document Tracking System");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Signup Here");

        jLabelUserId.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUserId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserId.setText("jLabel7");

        jLabelTodata.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTodata.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTodata.setText("jLabel7");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_tracking_system/images/Cancel_22px.png"))); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("username");

        jLabelSSID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSSID.setText("0");

        javax.swing.GroupLayout jPanel6ddLayout = new javax.swing.GroupLayout(jPanel6dd);
        jPanel6dd.setLayout(jPanel6ddLayout);
        jPanel6ddLayout.setHorizontalGroup(
            jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6ddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSSID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(jPanel6ddLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6ddLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelUserId)
                        .addGap(83, 83, 83)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6ddLayout.createSequentialGroup()
                        .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6ddLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6ddLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel7)
                                .addGap(150, 150, 150)
                                .addComponent(jLabelTodata)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6ddLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6ddLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6ddLayout.createSequentialGroup()
                                        .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6ddLayout.createSequentialGroup()
                                                .addComponent(jLabel32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel37))
                                            .addGroup(jPanel6ddLayout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6ddLayout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel31)))
                                        .addGap(7, 7, 7)))))))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel6ddLayout.setVerticalGroup(
            jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6ddLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6ddLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelUserId))
                    .addGroup(jPanel6ddLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6ddLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7))
                    .addComponent(jLabelTodata))
                .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6ddLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6ddLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6ddLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6ddLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelUsername)
                        .addContainerGap())
                    .addGroup(jPanel6ddLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jLabelSSID))))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Davao Oriental State University");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Document Tracking System");

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jPanel6dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel6dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_tracking_system/images/Exit_22px.png"))); // NOI18N
        jMenu1.setText("Exit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_tracking_system/images/About_22px.png"))); // NOI18N
        jMenu2.setText("How to use");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Manual");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_tracking_system/images/Helping Hand_22px.png"))); // NOI18N
        jMenu3.setText("Contact");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    RegisterPage reg;
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        try {
            if (reg == null || reg.isClosed()) {
                RegisterPage home = new RegisterPage();
                home.setVisible(true);
                dispose();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        login();

    }//GEN-LAST:event_jButtonSubmitActionPerformed
    public void login() {

        try {
            userGet();

            String username = jTextFieldUsername.getText();
            String password = jPasswordFieldPassword.getText();

            try {
                con = myConnection.getConnection();
                pst = con.prepareStatement("SELECT * FROM users WHERE username=? AND password=?");
                pst.setString(1, username);
                pst.setString(2, password);
                rs = pst.executeQuery();

                if (rs.next()) {
                    String s1 = rs.getString("permission");
                    String un = rs.getString("username");
                    if (username.equalsIgnoreCase("Admin")) {
                        String admin = "";
                        Admin home = new Admin(admin);

                        home.setVisible(true);
                        setVisible(false);
                    } else {

                        ReceiveSubmitPage home = new ReceiveSubmitPage(userGet());
                        home.setVisible(true);
                        home.jTextFieldBy.setText(userGet());
                        home.jLabelSSID.setText(userGetID());
                        home.jLabelField.setText(field());
                        home.jTextFieldFrom.setText(permission());
                        home.jButtonSubmit.setEnabled(false);
                        home.jLabelPermission.setText(permission());
                        ////=====================================================
                        if (home.jLabelPermission.getText().equalsIgnoreCase("President")) {
                            home.jComboBoxField.addItem("Send to All");
                        }
                        if (Integer.parseInt(trasactionHistoryNumber()) == 0) {
                            home.jLabelTransactionHistoryNumber.setVisible(false);
                            home.jLabelTransactionHistoryCircle.setVisible(false);

                        } else if (Integer.parseInt(trasactionHistoryNumber()) > 0) {
                            home.jLabelTransactionHistoryNumber.setText(trasactionHistoryNumber());
                            home.jLabelTransactionHistoryNumber.setVisible(true);
                            home.jLabelTransactionHistoryCircle.setVisible(true);
                        } else if (Integer.parseInt(trasactionHistoryNumber()) < 9) {
                            String var = "9+";
                            home.jLabelTransactionHistoryNumber.setText(var);
                            home.jLabelTransactionHistoryNumber.setVisible(true);
                            home.jLabelTransactionHistoryCircle.setVisible(true);
                        }
///////////////////////////////////////////////////////////////////////////////////////////////
                        if (Integer.parseInt(trackigPageNumber()) == 0) {
                            home.jLabeltrackingPageNumber.setVisible(false);
                            home.jLabelTrackingPageCircle.setVisible(false);

                        } else if (Integer.parseInt(trackigPageNumber()) > 0 && Integer.parseInt(trackigPageNumber()) < 9) {
                            home.jLabeltrackingPageNumber.setText(trackigPageNumber());
                            home.jLabeltrackingPageNumber.setVisible(true);
                            home.jLabelTrackingPageCircle.setVisible(true);
                        } else {
                            String var = "9+";
                            home.jLabeltrackingPageNumber.setText(var);
                            home.jLabeltrackingPageNumber.setVisible(true);
                            home.jLabelTrackingPageCircle.setVisible(true);
                        }
///////////////////////////////////////////////////////////////////////////////////////////////

                        if (Integer.parseInt(IncomingNotifyNumber()) == 0) {
                            home.jLabelIncomingNumber.setVisible(false);
                            home.jLabelIncomingCircle.setVisible(false);

                        } else if (Integer.parseInt(IncomingNotifyNumber()) > 0 && Integer.parseInt(IncomingNotifyNumber()) < 9) {
                            home.jLabelIncomingNumber.setText(IncomingNotifyNumber());
                            home.jLabelIncomingNumber.setVisible(true);
                            home.jLabelIncomingCircle.setVisible(true);
                        } else {
                            String var = "9+";
                            home.jLabelIncomingNumber.setText(var);
                            home.jLabelIncomingNumber.setVisible(true);
                            home.jLabelIncomingCircle.setVisible(true);
                        }
                        if (Integer.parseInt(PendingNotifyNumber()) == 0) {
                            home.jLabelPendingNumber.setVisible(false);
                            home.jLabelPendingCircle.setVisible(false);

                        } else if (Integer.parseInt(PendingNotifyNumber()) > 0 && Integer.parseInt(PendingNotifyNumber()) < 9) {
                            home.jLabelPendingNumber.setText(PendingNotifyNumber());
                            home.jLabelPendingNumber.setVisible(true);
                            home.jLabelPendingCircle.setVisible(true);
                        } else {
                            String var = "9+";
                            home.jLabelPendingNumber.setText(var);
                            home.jLabelPendingNumber.setVisible(true);
                            home.jLabelPendingCircle.setVisible(true);
                        }
///////////////////////////////////////////////////////////////////////////////////////////////
                        if (Integer.parseInt(OutgoingNotifyNumber()) == 0) {
                            home.jLabelOutgoingNumber.setVisible(false);
                            home.jLabelOutgoingCircle.setVisible(false);

                        } else if (Integer.parseInt(OutgoingNotifyNumber()) > 0 && Integer.parseInt(OutgoingNotifyNumber()) < 9) {
                            home.jLabelOutgoingNumber.setText(OutgoingNotifyNumber());
                            home.jLabelOutgoingNumber.setVisible(true);
                            home.jLabelOutgoingCircle.setVisible(true);
                        } else {
                            String var = "9+";
                            home.jLabelOutgoingNumber.setText(var);
                            home.jLabelOutgoingNumber.setVisible(true);
                            home.jLabelOutgoingCircle.setVisible(true);
                        }
                        dispose();

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Passwod not Match",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } catch (SQLException ex) {
            Logger.getLogger(LogInPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jPasswordFieldPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordKeyReleased
//        login();
    }//GEN-LAST:event_jPasswordFieldPasswordKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonSubmitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSubmitKeyReleased
        login();
    }//GEN-LAST:event_jButtonSubmitKeyReleased
    Manual log;
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            if (log == null || log.isClosed()) {
                Manual home = new Manual();
                home.setVisible(true);
                dispose();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabelSSID;
    private javax.swing.JLabel jLabelTodata;
    private javax.swing.JLabel jLabelUserId;
    public javax.swing.JLabel jLabelUsername;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6dd;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    boolean isClosed() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String userGet() throws SQLException {
        String username = jTextFieldUsername.getText();

        try {
            con = myConnection.getConnection();
            pst = con.prepareStatement("SELECT name, lastname  FROM `users` where username =?");
            pst.setString(1, username);
            rs = pst.executeQuery();

            if (rs.next()) {
                String firstname = rs.getString("name");
                String lastname = rs.getString("lastname");

                String userlog = firstname + " " + lastname;

//             
                return userlog;

            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    public String trackigPageNumber() throws SQLException {
        String var = jLabelUserId.getText();
        int number = Integer.parseInt(var);
        String all = "For Everyone";

        try {
            con = myConnection.getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM  trackingpage where userID ='" + number + "' or  to_data ='" + all + "'");

            if (rs.next()) {
                String sum = rs.getString("COUNT(*)");
                String userid = String.valueOf(sum);
                return userid;

            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    public String IncomingNotifyNumber() throws SQLException {

        String var = jLabelTodata.getText();
        //  int number = Integer.parseInt(var);
        //String username = jLabelUsername.getText();
        String all = "For Everyone";

        try {
            con = myConnection.getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM  incoming where to_data ='" + var + "' or to_data ='" + userGet() + "' or to_data ='" + all + "' && by_data !='" + userGet() + "'");

            if (rs.next()) {
                String sum = rs.getString("COUNT(*)");
                String userid = String.valueOf(sum);
                return userid;

            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    public String PendingNotifyNumber() throws SQLException {

        String var = jLabelTodata.getText();
        //  int number = Integer.parseInt(var);
        String all = "For Everyone";

        try {
            con = myConnection.getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM pending where to_data ='" + var + "' or to_data ='" + userGet() + "' or to_data ='" + all + "'");

            if (rs.next()) {
                String sum = rs.getString("COUNT(*)");
                String userid = String.valueOf(sum);
                return userid;
            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    public String OutgoingNotifyNumber() throws SQLException {

        //String var = jLabelTodata.getText();
        //  int number = Integer.parseInt(var);
        String all = "For Everyone";

        try {
            con = myConnection.getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM outgoing where forwarded_by  ='" + userGet() + "' or to_data ='" + all + "'");

            if (rs.next()) {
                String sum = rs.getString("COUNT(*)");
                String userid = String.valueOf(sum);
                return userid;
            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    public String trasactionHistoryNumber() throws SQLException {
        String var = jLabelUserId.getText();
        int number = Integer.parseInt(var);
        String all = "For Everyone";

        try {
            con = myConnection.getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM  trackinghistory where userID ='" + number + "' or to_data ='" + number + "' or to_data ='" + userGet() + "' or to_data ='" + all + "'");

            if (rs.next()) {
                String sum = rs.getString("COUNT(*)");
                String userid = String.valueOf(sum);
                return userid;

            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    public String trasactionHistoryNumberPresident() throws SQLException {
        String var = "School President";
        // int number = Integer.parseInt(var);

        try {
            con = myConnection.getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM  trackinghistory where to_data ='" + var + "'");

            if (rs.next()) {
                String sum = rs.getString("COUNT(*)");
                String userid = String.valueOf(sum);
                return userid;

            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    public String userGetID() throws SQLException {
        String username = jTextFieldUsername.getText();

        try {
            con = myConnection.getConnection();
            pst = con.prepareStatement("SELECT id, name,permission, lastname  FROM `users` where username =?");
            pst.setString(1, username);
            rs = pst.executeQuery();

            if (rs.next()) {
                int id = rs.getInt("id");
                String per = rs.getString("permission");
                String userid = String.valueOf(id);
                jLabelTodata.setText(per);
                jLabelUserId.setText(userid);
                return userid;

            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    public String field() throws SQLException {
        String username = jTextFieldUsername.getText();

        try {
            con = myConnection.getConnection();
            pst = con.prepareStatement("SELECT field  FROM `users` where username =?");
            pst.setString(1, username);
            rs = pst.executeQuery();

            if (rs.next()) {
                String fi = rs.getString("field");
                String userid = String.valueOf(fi);
                return userid;

            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    public String permission() throws SQLException {
        String username = jTextFieldUsername.getText();

        try {
            con = myConnection.getConnection();
            pst = con.prepareStatement("SELECT permission  FROM `users` where username =?");
            pst.setString(1, username);
            rs = pst.executeQuery();

            if (rs.next()) {
                String fi = rs.getString("permission");
                String userid = String.valueOf(fi);
                return userid;

            } else {
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LogInPage().setVisible(true);
//            }
//        }
//        );
//    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInPage().setVisible(true);
            }
        }
        );
    }
}
